apiVersion: operator.tf.mirantis.com/v1alpha1
kind: TFOperator
metadata:
  name: example-tfoperator
spec:
  tf-config:
    api:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-kubernetes-kube-manager:5.1-4.15.0-54-generic
      env:
        - name: TF_SANDESH_SEND_RATE_LIMIT
          value: 100

    svc-monitor:
      replicas: 1
      image: willco/opencontrail-config-svc-monitor:r5.1
      ports:
        - name: introspect
          port: 8088

    schema:
      replicas: 1
      image: willco/opencontrail-config-schema:r5.1

    devicemgr:
      replicas: 1
      image: willco/opencontrail-config-devicemgr:r5.1
      ports:
        - name: introspect
          port: 8087
