apiVersion: operator.tf.mirantis.com/v1alpha1
kind: TFOperator
metadata:
  name: example-tfoperator
spec:
  tf-config:
    api:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-controller-config-api:5.1-4.15.0-54-generic
      ports:
        - name: api
          port: 9100
        - name: introspect
          port: 8084
      env:
        - name: TF_SANDESH_SEND_RATE_LIMIT
          value: "100"

    svc-monitor:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-controller-config-svcmonitor:5.1-4.15.0-54-generic
      ports:
        - name: introspect
          port: 8088

    schema:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-controller-config-schema:5.1-4.15.0-54-generic

    devicemgr:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-controller-config-devicemgr:5.1-4.15.0-54-generic
      ports:
        - name: introspect
          port: 8087
  tf-control:
    control:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-controller-control-control:5.1-4.15.0-54-generic

    named:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-controller-control-named:5.1-4.15.0-54-generic
      securityContext:
        capabilities: ["DAC_READ_SEARCH", "SYS_RESOURCE"]

    dns:
      replicas: 1
      image: docker-dev-local.docker.mirantis.net/opencontrail-exp-5.1-upstream/contrail-controller-control-dns:5.1-4.15.0-54-generic
