// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/Svimba/tungstenfabric-operator/pkg/apis/analytics/v1alpha1.TFAnalytics":       schema_pkg_apis_analytics_v1alpha1_TFAnalytics(ref),
		"github.com/Svimba/tungstenfabric-operator/pkg/apis/analytics/v1alpha1.TFAnalyticsSpec":   schema_pkg_apis_analytics_v1alpha1_TFAnalyticsSpec(ref),
		"github.com/Svimba/tungstenfabric-operator/pkg/apis/analytics/v1alpha1.TFAnalyticsStatus": schema_pkg_apis_analytics_v1alpha1_TFAnalyticsStatus(ref),
	}
}

func schema_pkg_apis_analytics_v1alpha1_TFAnalytics(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TFAnalytics is the Schema for the tfanalytics API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Svimba/tungstenfabric-operator/pkg/apis/analytics/v1alpha1.TFAnalyticsSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Svimba/tungstenfabric-operator/pkg/apis/analytics/v1alpha1.TFAnalyticsStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/Svimba/tungstenfabric-operator/pkg/apis/analytics/v1alpha1.TFAnalyticsSpec", "github.com/Svimba/tungstenfabric-operator/pkg/apis/analytics/v1alpha1.TFAnalyticsStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_analytics_v1alpha1_TFAnalyticsSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TFAnalyticsSpec defines the desired state of TFAnalytics",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_analytics_v1alpha1_TFAnalyticsStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TFAnalyticsStatus defines the observed state of TFAnalytics",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
