// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Port) DeepCopyInto(out *Port) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Port.
func (in *Port) DeepCopy() *Port {
	if in == nil {
		return nil
	}
	out := new(Port)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalytics) DeepCopyInto(out *TFAnalytics) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalytics.
func (in *TFAnalytics) DeepCopy() *TFAnalytics {
	if in == nil {
		return nil
	}
	out := new(TFAnalytics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TFAnalytics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsAPISpec) DeepCopyInto(out *TFAnalyticsAPISpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.EnvList != nil {
		in, out := &in.EnvList, &out.EnvList
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsAPISpec.
func (in *TFAnalyticsAPISpec) DeepCopy() *TFAnalyticsAPISpec {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsAlarmGenSpec) DeepCopyInto(out *TFAnalyticsAlarmGenSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.EnvList != nil {
		in, out := &in.EnvList, &out.EnvList
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsAlarmGenSpec.
func (in *TFAnalyticsAlarmGenSpec) DeepCopy() *TFAnalyticsAlarmGenSpec {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsAlarmGenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsCollectorSpec) DeepCopyInto(out *TFAnalyticsCollectorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.EnvList != nil {
		in, out := &in.EnvList, &out.EnvList
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsCollectorSpec.
func (in *TFAnalyticsCollectorSpec) DeepCopy() *TFAnalyticsCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsList) DeepCopyInto(out *TFAnalyticsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TFAnalytics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsList.
func (in *TFAnalyticsList) DeepCopy() *TFAnalyticsList {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TFAnalyticsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsQueryEngineSpec) DeepCopyInto(out *TFAnalyticsQueryEngineSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.EnvList != nil {
		in, out := &in.EnvList, &out.EnvList
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsQueryEngineSpec.
func (in *TFAnalyticsQueryEngineSpec) DeepCopy() *TFAnalyticsQueryEngineSpec {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsQueryEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsSNMPSpec) DeepCopyInto(out *TFAnalyticsSNMPSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.EnvList != nil {
		in, out := &in.EnvList, &out.EnvList
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsSNMPSpec.
func (in *TFAnalyticsSNMPSpec) DeepCopy() *TFAnalyticsSNMPSpec {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsSNMPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsSpec) DeepCopyInto(out *TFAnalyticsSpec) {
	*out = *in
	in.AlarmGenSpec.DeepCopyInto(&out.AlarmGenSpec)
	in.APISpec.DeepCopyInto(&out.APISpec)
	in.CollectorSpec.DeepCopyInto(&out.CollectorSpec)
	in.QueryEngine.DeepCopyInto(&out.QueryEngine)
	in.SNMPSpec.DeepCopyInto(&out.SNMPSpec)
	in.TopologySpec.DeepCopyInto(&out.TopologySpec)
	if in.ConfigMapList != nil {
		in, out := &in.ConfigMapList, &out.ConfigMapList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsSpec.
func (in *TFAnalyticsSpec) DeepCopy() *TFAnalyticsSpec {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsStatus) DeepCopyInto(out *TFAnalyticsStatus) {
	*out = *in
	if in.ConfigMapList != nil {
		in, out := &in.ConfigMapList, &out.ConfigMapList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsStatus.
func (in *TFAnalyticsStatus) DeepCopy() *TFAnalyticsStatus {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFAnalyticsTopologySpec) DeepCopyInto(out *TFAnalyticsTopologySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.EnvList != nil {
		in, out := &in.EnvList, &out.EnvList
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFAnalyticsTopologySpec.
func (in *TFAnalyticsTopologySpec) DeepCopy() *TFAnalyticsTopologySpec {
	if in == nil {
		return nil
	}
	out := new(TFAnalyticsTopologySpec)
	in.DeepCopyInto(out)
	return out
}
